version: "2"
services:
  opportunities:
    build: .
    restart: always
    container_name: opportunities
    volumes:
      - ".:/opportunities"
      - "./node_modules:/opportunities/node_modules"
    ports:
      - "3000:3000"
      - "9229:9229"
    command: /bin/bash -c -l "npm install && npm run inspect"
